apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rachneet/kubernetes-argocd.git
    targetRevision: HEAD
    path: configs/nfs_storage
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
