image:
  name: traefik
  tag: "2.5.3"

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

additionalArguments:
  - "--certificatesresolvers.le-staging.acme.tlschallenge=true"
  - "--certificatesresolvers.le-staging.acme.email=rachneetsachdeva@yahoo.com"
  - "--certificatesresolvers.le-staging.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--metrics.prometheus=true"
    # - "--certificatesresolvers.le.acme.tlschallenge=true"
    # - "--certificatesresolvers.le.acme.email=rachneetsachdeva@yahoo.com"
    # - "--certificatesresolvers.le.acme.storage=/data/acme.json"

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 128Mi
  storageClass: "managed-nfs-storage"

metrics:
  prometheus:
    enabled: true
#        serviceMonitor:
#          # When set true and if Prometheus Operator is installed then use a ServiceMonitor to configure scraping
#          enabled: true
#          # Set the namespace the ServiceMonitor should be deployed
#          namespace: monitoring
#          # Set how frequently Prometheus should scrape
#          interval: 10s

logs:
  access:
    enabled: true
    format: json