apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- middleware.yaml
namespace: default
replicas:
- count: 1
  name: demo-app
images:
- name: demo-app
  newName: rachneet4/simple-flask-app2
  newTag: latest
- name: rachneet4/test-app:latest
  newName: rachneet4/simple-flask-app2
  newTag: latest
